In [2]:
import pandas as pd

In [23]:
df=pd.read_excel(r'C:/Users/areeba abid/Downloads/corona-virus-pakistan-dataset-2020 (1)/COVID_FINAL_DATA.xlsx',sheet_name='TimeSeries_KeyIndicators_Detail')
df_pakistan=df.copy()
df

,Date,Province Old,Suspected Cases Last Date,Suspected Cases Last 24 Hrs,Suspected Cases Cumulative,Lab Tests Last 24 Hrs,Lab Tests Cumulative,Confirmed Cases Last Date,Confirmed Cases Last 24 Hrs,Confirmed Cases Cumulative,...,Confirmed HW - Active Doctors,Confirmed HW - Active Nurses,Confirmed HW - Active Others,Confirmed HW - Active Total,Confirmed HW - Active Isolation,Confirmed HW - Active Hospital,Confirmed HW - Active Hospital Stable,Confirmed HW - Active Hospital Ventilator,Confirmed HW - Active Recovered,Confirmed HW - Active Deaths
0,2020-04-04,AJK,322,21,343,21,343,9,2,11,...,0,0,0,0,0,0,0,0,0,0
1,2020-04-04,Balochistan,2171,230,2401,0,2401,169,6,175,...,0,0,0,0,0,0,0,0,0,0
2,2020-04-04,GB,961,2,963,844,860,190,3,193,...,0,0,0,0,0,0,0,0,0,0
3,2020-04-04,ICT,2395,174,2569,174,2569,68,7,75,...,0,0,0,0,0,0,0,0,0,0
4,2020-04-04,KP,1938,431,2369,181,1624,311,32,343,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,2020-05-05,GB,5069,91,5160,142,4581,364,8,372,...,1,1,18,20,0,6,6,0,12,2
206,2020-05-05,ICT,12704,993,13697,993,13697,415,49,464,...,28,12,15,55,46,2,2,0,6,1
207,2020-05-05,KP,20900,783,21683,783,22692,3129,159,3288,...,69,20,40,129,99,6,6,0,22,2
208,2020-05-05,Punjab,67908,6625,74533,5043,101897,7524,579,8103,...,58,21,23,102,14,50,50,0,38,0
209,2020-05-05,Sindh,64052,2571,66623,2571,66623,7465,417,7882,...,44,17,37,98,0,66,66,0,28,4

In [22]:
df=pd.read_excel(r'C:/Users/areeba abid/Downloads/corona-virus-pakistan-dataset-2020 (1)/COVID_FINAL_DATA.xlsx',sheet_name='TimeSeries_KeyIndicators_Detail')
df_pakistan=df.copy()
df

,Date,Province Old,Suspected Cases Last Date,Suspected Cases Last 24 Hrs,Suspected Cases Cumulative,Lab Tests Last 24 Hrs,Lab Tests Cumulative,Confirmed Cases Last Date,Confirmed Cases Last 24 Hrs,Confirmed Cases Cumulative,...,Confirmed HW - Active Doctors,Confirmed HW - Active Nurses,Confirmed HW - Active Others,Confirmed HW - Active Total,Confirmed HW - Active Isolation,Confirmed HW - Active Hospital,Confirmed HW - Active Hospital Stable,Confirmed HW - Active Hospital Ventilator,Confirmed HW - Active Recovered,Confirmed HW - Active Deaths
0,2020-04-04,AJK,322,21,343,21,343,9,2,11,...,0,0,0,0,0,0,0,0,0,0
1,2020-04-04,Balochistan,2171,230,2401,0,2401,169,6,175,...,0,0,0,0,0,0,0,0,0,0
2,2020-04-04,GB,961,2,963,844,860,190,3,193,...,0,0,0,0,0,0,0,0,0,0
3,2020-04-04,ICT,2395,174,2569,174,2569,68,7,75,...,0,0,0,0,0,0,0,0,0,0
4,2020-04-04,KP,1938,431,2369,181,1624,311,32,343,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,2020-05-05,GB,5069,91,5160,142,4581,364,8,372,...,1,1,18,20,0,6,6,0,12,2
206,2020-05-05,ICT,12704,993,13697,993,13697,415,49,464,...,28,12,15,55,46,2,2,0,6,1
207,2020-05-05,KP,20900,783,21683,783,22692,3129,159,3288,...,69,20,40,129,99,6,6,0,22,2
208,2020-05-05,Punjab,67908,6625,74533,5043,101897,7524,579,8103,...,58,21,23,102,14,50,50,0,38,0
209,2020-05-05,Sindh,64052,2571,66623,2571,66623,7465,417,7882,...,44,17,37,98,0,66,66,0,28,4

In [22]:
df=pd.read_excel(r'C:/Users/areeba abid/Downloads/corona-virus-pakistan-dataset-2020 (1)/COVID_FINAL_DATA.xlsx',sheet_name='TimeSeries_Action_Screen')
df_pakistan=df.copy()
df

,Date,Cumulative travelers Screened,Suspected at Points of Entry,Travelers Screened at Points ofEntry in last 24 hours
0,11-Mar-2020,873288,26,21102
1,12-Mar-2020,894256,29,20968
2,13-Mar-2020,913542,33,19286
3,14-Mar-2020,933970,43,20428
4,15-Mar-2020,954646,59,20676
5,16-Mar-2020,975634,74,20988
6,17-Mar-2020,995821,95,20187
7,18-Mar-2020,1015909,115,20088
8,19-Mar-2020,1033884,151,17975
9,20-Mar-2020,1049282,170,15398
10,21-Mar-2020,1063193,186,13911
11,22-Mar-2020,1077632,202,14439
12,23-Mar-2020,1089933,217,12301
13,24-Mar-2020,1102234,232,12301
14,25-Mar-2020,1102383,234,149
15,26-Mar-2020,1102383,234,0
16,27-Mar-2020,1102383,234,0
17,28-Mar-2020,1102383,234,0
18,29-Mar-2020,1102383,234,0
19,2020-03-30 00:00:00,1102562,234,0
20,2020-03-31 00:00:00,1102562,234,0
21,2020-04-01 00:00:00,1102562,234,0
22,2020-04-02 00:00:00,1102562,234,0
23,2020-04-03 00:00:00,1102562,234,0

In [21]:
df=pd.read_excel(r'C:/Users/areeba abid/Downloads/corona-virus-pakistan-dataset-2020 (1)/COVID_FINAL_DATA.xlsx',sheet_name='TimeSeries_Action_Call')
df_pakistan=df.copy()
df

,Returnees,Advised Self-Quarantine,Cumulative no offirst-time calls,Cumulativefollow-up calls,Date,First-time calls inpast 24 hrs,Follow-up calls inpast 24 hrs
0,Returnees from Iran,0,9459,2553,11-Mar-2020,0,353
1,Returnees from China,11,5342,7746,11-Mar-2020,17,400
2,Returnees from Iran,14,9475,3221,12-Mar-2020,16,668
3,Returnees from China,7,5352,7855,12-Mar-2020,10,109
4,Returnees from Iran,0,9475,3853,13-Mar-2020,0,632
5,Returnees from China,10,5362,8041,13-Mar-2020,10,186
6,Returnees from Iran,3,9480,4182,14-Mar-2020,5,329
7,Returnees from China,5,5370,8083,14-Mar-2020,8,42
8,Returnees from Iran,0,9480,4625,15-Mar-2020,0,443
9,Returnees from China,0,5370,8160,15-Mar-2020,0,77
10,Returnees from Iran,3,9488,4625,16-Mar-2020,8,0
11,Returnees from China,11,5394,8160,16-Mar-2020,24,0
12,Returnees from Iran,0,9488,5063,17-Mar-2020,0,438
13,Returnees from China,13,5413,8180,17-Mar-2020,19,20
14,Returnees from Iran,0,9488,5337,18-Mar-2020,0,274
15,Returnees from China,16,5439,8899,18-Mar-2020,26,719
16,Returnees from Iran,0,9488,5337,19-Mar-2020,0,32
17,Returnees from China,0,5441,9392,19-Mar-2020,2,493
18,Returnees from Iran,0,9488,5623,20-Mar-2020,0,286
19,Returnees from China,8,5458,9392,20-Mar-2020,17,0
20,Returnees from Iran,1,9489,5977,21-Mar-2020,1,354
21,Returnees from China,1,5462,9658,21-Mar-2020,4,266
22,Returnees from Iran,0,9489,6116,22-Mar-2020,0,139
23,Returnees from China,3,5473,10109,22-Mar-2020,11,451
24,Returnees from Iran,0,9489,6289,23-Mar-2020,0,173
25,Returnees from China,1,5474,10451,23-Mar-2020,1,342
26,Returnees from Iran,0,9489,6289,24-Mar-2020,0,0
27,Returnees from China,0,5474,10875,24-Mar-2020,0,424
28,Returnees from Iran,0,9489,6474,25-Mar-2020,0,185
29,Returnees from China,0,5474,11110,25-Mar-2020,0,235
30,Returnees from Iran,0,9489,6890,26-Mar-2020,0,416
31,Returnees from China,0,5474,11460,26-Mar-2020,0,350
32,Returnees from Iran,0,9489,6923,27-Mar-2020,0,133
33,Returnees from China,0,5474,11727,27-Mar-2020,0,267
34,Returnees from Iran,0,9489,7115,28-Mar-2020,0,192
35,Returnees from China,0,5474,12247,28-Mar-2020,0,520
36,Returnees from Iran,0,9489,7115,29-Mar-2020,0,0
37,Returnees from China,0,5474,12409,29-Mar-2020,0,162
38,Returnees from Iran,0,9489,7215,30-Mar-2020,0,100
39,Returnees from China,0,5474,12480,30-Mar-2020,0,71

In [27]:
df=pd.read_excel(r'C:/Users/areeba abid/Downloads/corona-virus-pakistan-dataset-2020 (1)/COVID_FINAL_DATA.xlsx',sheet_name='TimeSeries_COVID_News')
df_pakistan=df.copy()
df

,Unnamed: 0,Date,News,Agg News
0,0,11-Mar-2020,Updates: Pakistan:,Updates: Pakistan: \n Three new cases have bee...
1,1,11-Mar-2020,Three new cases have been confirmed in the pas...,Updates: Pakistan: \n Three new cases have bee...
2,2,11-Mar-2020,Number of calls to passengers returning from I...,Updates: Pakistan: \n Three new cases have bee...
3,3,11-Mar-2020,Global:,Updates: Pakistan: \n Three new cases have bee...
4,4,11-Mar-2020,"Total cases: 118,887, Total Deaths: 4,290 â€¢",Updates: Pakistan: \n Three new cases have bee...
...,...,...,...,...
141,2,2020-04-03 00:00:00,"2,450. Two deaths reported from Sindh. One dea...","Updates: Pakistan: \n During last 24 hours, 15..."
142,3,2020-04-03 00:00:00,deaths 35. â€¢,"Updates: Pakistan: \n During last 24 hours, 15..."
143,4,2020-04-03 00:00:00,Global:,"Updates: Pakistan: \n During last 24 hours, 15..."
144,5,2020-04-03 00:00:00,"Total cases:1,015,709 Total Deaths: 53,069 â€¢","Updates: Pakistan: \n During last 24 hours, 15..."
145,6,2020-04-03 00:00:00,Total number of countries/regions affected: 181 â€¢,"Updates: Pakistan: \n During last 24 hours, 15..."

In [26]:
df=pd.read_excel(r'C:/Users/areeba abid/Downloads/corona-virus-pakistan-dataset-2020 (1)/COVID_FINAL_DATA.xlsx',sheet_name='TimeSeries_NIH_Response')
df_pakistan=df.copy()
df

,Unnamed: 0,Date,NIH Preparedness and Response,Agg NIH Preparedness and Response
0,0,11-Mar-2020,BSL-3 mobile lab with state of art equipment h...,BSL-3 mobile lab with state of art equipment h...
1,1,11-Mar-2020,IPC trainings have been completed at Gilgit an...,BSL-3 mobile lab with state of art equipment h...
2,2,11-Mar-2020,Training of the GB lab staff has been conducte...,BSL-3 mobile lab with state of art equipment h...
3,3,11-Mar-2020,IPC training is in progress for FG Hospital st...,BSL-3 mobile lab with state of art equipment h...
4,0,12-Mar-2020,BSL-3 mobile lab is ready for testing. â€¢,BSL-3 mobile lab is ready for testing. â€¢ \n I...
...,...,...,...,...
60,1,2020-04-02 00:00:00,Risk communication carried out among healthcar...,Contact tracing of confirmed cases being carri...
61,2,2020-04-02 00:00:00,NIH laboratory is providing support to provinc...,Contact tracing of confirmed cases being carri...
62,0,2020-04-03 00:00:00,Contact tracing of confirmed cases being carri...,Contact tracing of confirmed cases being carri...
63,1,2020-04-03 00:00:00,Risk communication carried out among healthcar...,Contact tracing of confirmed cases being carri...
64,2,2020-04-03 00:00:00,NIH laboratory is providing support to provinc...,Contact tracing of confirmed cases being carri...

In [23]:
df=pd.read_excel(r'C:/Users/areeba abid/Downloads/corona-virus-pakistan-dataset-2020 (1)/COVID_FINAL_DATA.xlsx',sheet_name='TimeSeries_NIH_Risk')
df_pakistan=df.copy()
df

    Unnamed: 0                 Date Risk Assessment NIH
0            0          11-Mar-2020           MODERATE.
1            0          12-Mar-2020           MODERATE.
2            0          13-Mar-2020           MODERATE.
3            0          14-Mar-2020           MODERATE.
4            0          15-Mar-2020            Moderate
5            0          16-Mar-2020            Moderate
6            0          17-Mar-2020            Moderate
7            0          18-Mar-2020            Moderate
8            0          19-Mar-2020                High
9            0          20-Mar-2020                High
10           0          21-Mar-2020                High
11           0          22-Mar-2020                High
12           0          23-Mar-2020                High
13           0          24-Mar-2020                High
14           0          25-Mar-2020                High
15           0          26-Mar-2020                High
16           0          27-Mar-2020                High
17           0          28-Mar-2020                High
18           0          29-Mar-2020                High
19           0          30-Mar-2020                High
20           0  2020-03-31 00:00:00                High
21           0  2020-04-01 00:00:00                High
22           0  2020-04-02 00:00:00                High
23           0  2020-04-03 00:00:00                High

In [25]:
df=pd.read_excel(r'C:/Users/areeba abid/Downloads/corona-virus-pakistan-dataset-2020 (1)/COVID_FINAL_DATA.xlsx',sheet_name='TimeSeries_Province_Response')
df_pakistan=df.copy()
df

,Unnamed: 0,region,Provinces Preparedness and Response,Date,Agg Provinces Preparedness and Response
0,0,Balochistan,316 newly arrived individuals screened and qua...,11-Mar-2020,316 newly arrived individuals screened and qua...
1,1,Balochistan,14 Chinese nationals quarantined at East Bay E...,11-Mar-2020,316 newly arrived individuals screened and qua...
2,2,Sindh,Staff deployed to designated quarantine facili...,11-Mar-2020,Staff deployed to designated quarantine facili...
3,3,Sindh,Training and orientation sessions for the heal...,11-Mar-2020,Staff deployed to designated quarantine facili...
4,4,KP & TD,24 High Dependency Units established across KP...,11-Mar-2020,24 High Dependency Units established across KP...
...,...,...,...,...,...
161,2,Sindh,Sindh Government has disbursed Rs.569.604 mill...,2020-04-03 00:00:00,Sindh Government has disbursed Rs.569.604 mill...
162,3,Punjab,District level trainings of HDU/Isolation/Quar...,2020-04-03 00:00:00,District level trainings of HDU/Isolation/Quar...
163,4,KP,Data transcription on to the IPMS software hos...,2020-04-03 00:00:00,Data transcription on to the IPMS software hos...
164,5,AJK,"Out of 9 confirmed cases, 6 are local transmis...",2020-04-03 00:00:00,"Out of 9 confirmed cases, 6 are local transmis..."
165,6,GB,Involvement of WHO staff to provide support in...,2020-04-03 00:00:00,Involvement of WHO staff to provide support in...

In [28]:
df=pd.read_excel(r'C:/Users/areeba abid/Downloads/corona-virus-pakistan-dataset-2020 (1)/COVID_FINAL_DATA.xlsx',sheet_name='TimeSeries_Helpline_Calls')
df_pakistan=df.copy()
df

    Unnamed: 0  Cumulative Calls       Date  New Calls
0            0             12481 2020-03-11        547
1            0             13167 2020-03-12        686
2            0             13896 2020-03-13        729
3            0             15340 2020-03-14       1444
4            0             19131 2020-03-15       3791
5            0             26193 2020-03-16       7062
6            0             33427 2020-03-17       7234
7            0             41563 2020-03-18       8136
8            0             48786 2020-03-19       7223
9            0             56892 2020-03-20       8106
10           0             65602 2020-03-21       8710
11           0             65602 2020-03-22       8710
12           0             84700 2020-03-23       9654
13           0             93991 2020-03-24       9291
14           0            110052 2020-03-25      16061
15           0            152633 2020-03-26      42581
16           0            152633 2020-03-27          0
17           0            321600 2020-03-28     138062
18           0            449289 2020-03-29     128229
19           0            531628 2020-03-30      82799
20           0            620574 2020-03-31      88946
21           0            700728 2020-04-01      80154
22           0            772723 2020-04-02      71995
23           0            840021 2020-04-03      67298

In [29]:
df=pd.read_excel(r'C:/Users/areeba abid/Downloads/corona-virus-pakistan-dataset-2020 (1)/COVID_FINAL_DATA.xlsx',sheet_name='TimeSeries_Quarantine_Details')
df_pakistan=df.copy()
df

,Unnamed: 0,Regions,Quarantine facilities (n),No. of arrivals in last 24 hrs,Cumulative no of persons present,Date
0,0,ICT,1,0,24,2020-04-01
1,1,Punjab,4,0,2956,2020-04-01
2,2,Sindh,5,0,1388,2020-04-01
3,3,KP,92,181,3260,2020-04-01
4,4,Balochistan,9,0,366,2020-04-01
5,5,AJK,13,210,373,2020-04-01
6,6,GB,47,0,526,2020-04-01
7,0,ICT,1,7,31,2020-04-02
8,1,Punjab,4,0,2956,2020-04-02
9,2,Sindh,5,0,1365,2020-04-02
10,3,KP,98,98,3223,2020-04-02
11,4,Balochistan,9,0,364,2020-04-02
12,5,AJK,37,5,188,2020-04-02
13,6,GB,47,3,529,2020-04-02
14,0,ICT,6,0,30,2020-04-03
15,1,Punjab,4,0,2956,2020-04-03
16,2,Sindh,5,0,1363,2020-04-03
17,3,KP,101,279,3312,2020-04-03
18,4,Balochistan,9,0,408,2020-04-03
19,5,AJK,37,22,197,2020-04-03
20,6,GB,47,0,227,2020-04-03

In [9]:
all_df.keys()

odict_keys(['TimeSeries_KeyIndicators', 'TimeSeries_KeyIndicators_Detail', 'TimeSeries_Action_Screen', 'TimeSeries_Action_Call', 'TimeSeries_COVID_News', 'TimeSeries_NIH_Response', 'TimeSeries_NIH_Risk', 'TimeSeries_Province_Response', 'TimeSeries_Helpline_Calls', 'TimeSeries_Quarantine_Details'])